//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spacebuilder.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Spacebuilder.Web.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 使用{0}登录了网站“{1}”{2} 的本地化字符串。
        /// </summary>
        public static string AccountBinding_ShareToFirend {
            get {
                return ResourceManager.GetString("AccountBinding_ShareToFirend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 频道 的本地化字符串。
        /// </summary>
        public static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 被管理员惩罚 的本地化字符串。
        /// </summary>
        public static string Common_AdminPunish {
            get {
                return ResourceManager.GetString("Common_AdminPunish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 被管理员奖励 的本地化字符串。
        /// </summary>
        public static string Common_AdminReward {
            get {
                return ResourceManager.GetString("Common_AdminReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匿名用户 的本地化字符串。
        /// </summary>
        public static string Common_AnonymousDisplayName {
            get {
                return ResourceManager.GetString("Common_AnonymousDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前天 的本地化字符串。
        /// </summary>
        public static string Common_BeforeYesterday {
            get {
                return ResourceManager.GetString("Common_BeforeYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - 的本地化字符串。
        /// </summary>
        public static string Common_BrowserTitleSeparator {
            get {
                return ResourceManager.GetString("Common_BrowserTitleSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ： 的本地化字符串。
        /// </summary>
        public static string Common_Colon {
            get {
                return ResourceManager.GetString("Common_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - 的本地化字符串。
        /// </summary>
        public static string Common_DateTimeWhenZero {
            get {
                return ResourceManager.GetString("Common_DateTimeWhenZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyy-MM-dd 的本地化字符串。
        /// </summary>
        public static string Common_DefaultDateFormat {
            get {
                return ResourceManager.GetString("Common_DefaultDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HH:mm 的本地化字符串。
        /// </summary>
        public static string Common_DefaultTimeFormat {
            get {
                return ResourceManager.GetString("Common_DefaultTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常URL：{0} 的本地化字符串。
        /// </summary>
        public static string Common_ExceptionUrl {
            get {
                return ResourceManager.GetString("Common_ExceptionUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 他 的本地化字符串。
        /// </summary>
        public static string Common_He {
            get {
                return ResourceManager.GetString("Common_He", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Http传输方式：{0} 的本地化字符串。
        /// </summary>
        public static string Common_HttpMethod {
            get {
                return ResourceManager.GetString("Common_HttpMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 现在 的本地化字符串。
        /// </summary>
        public static string Common_Now {
            get {
                return ResourceManager.GetString("Common_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - 的本地化字符串。
        /// </summary>
        public static string Common_NumberWhenZero {
            get {
                return ResourceManager.GetString("Common_NumberWhenZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;lt;&amp;lt; 的本地化字符串。
        /// </summary>
        public static string Common_PagerFirstButton {
            get {
                return ResourceManager.GetString("Common_PagerFirstButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;gt;&amp;gt; 的本地化字符串。
        /// </summary>
        public static string Common_PagerLastButton {
            get {
                return ResourceManager.GetString("Common_PagerLastButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一页 的本地化字符串。
        /// </summary>
        public static string Common_PagerNextButton {
            get {
                return ResourceManager.GetString("Common_PagerNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一页 的本地化字符串。
        /// </summary>
        public static string Common_PagerPreviousButton {
            get {
                return ResourceManager.GetString("Common_PagerPreviousButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}月{1}日{2} 的本地化字符串。
        /// </summary>
        public static string Common_Pattern_CNMonthDay {
            get {
                return ResourceManager.GetString("Common_Pattern_CNMonthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}天之前 的本地化字符串。
        /// </summary>
        public static string Common_Pattern_DayAgo {
            get {
                return ResourceManager.GetString("Common_Pattern_DayAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}小时之前 的本地化字符串。
        /// </summary>
        public static string Common_Pattern_HoursAgo {
            get {
                return ResourceManager.GetString("Common_Pattern_HoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}分钟之前 的本地化字符串。
        /// </summary>
        public static string Common_Pattern_MinutelAgo {
            get {
                return ResourceManager.GetString("Common_Pattern_MinutelAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}秒之前 的本地化字符串。
        /// </summary>
        public static string Common_Pattern_SecondsAgo {
            get {
                return ResourceManager.GetString("Common_Pattern_SecondsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 积分交易 的本地化字符串。
        /// </summary>
        public static string Common_PointTrade {
            get {
                return ResourceManager.GetString("Common_PointTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 惩罚用户 的本地化字符串。
        /// </summary>
        public static string Common_PunishUser {
            get {
                return ResourceManager.GetString("Common_PunishUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 奖励用户 的本地化字符串。
        /// </summary>
        public static string Common_RewardUser {
            get {
                return ResourceManager.GetString("Common_RewardUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 她 的本地化字符串。
        /// </summary>
        public static string Common_She {
            get {
                return ResourceManager.GetString("Common_She", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ta 的本地化字符串。
        /// </summary>
        public static string Common_Ta {
            get {
                return ResourceManager.GetString("Common_Ta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 今天 的本地化字符串。
        /// </summary>
        public static string Common_TodayAt {
            get {
                return ResourceManager.GetString("Common_TodayAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易税 的本地化字符串。
        /// </summary>
        public static string Common_TransactionTax {
            get {
                return ResourceManager.GetString("Common_TransactionTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户代理信息：{0} 的本地化字符串。
        /// </summary>
        public static string Common_UserAgent {
            get {
                return ResourceManager.GetString("Common_UserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户IP：{0} 的本地化字符串。
        /// </summary>
        public static string Common_UserIP {
            get {
                return ResourceManager.GetString("Common_UserIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昨天 的本地化字符串。
        /// </summary>
        public static string Common_YesterdayAt {
            get {
                return ResourceManager.GetString("Common_YesterdayAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后台 的本地化字符串。
        /// </summary>
        public static string ControlPanel {
            get {
                return ResourceManager.GetString("ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有足够的访问权限 的本地化字符串。
        /// </summary>
        public static string Exception_AccessDenied {
            get {
                return ResourceManager.GetString("Exception_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有管理{0}的权限 的本地化字符串。
        /// </summary>
        public static string Exception_BasicManagementAccessDenied {
            get {
                return ResourceManager.GetString("Exception_BasicManagementAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “{0}”不存在或已被删除，Id:{1} 的本地化字符串。
        /// </summary>
        public static string Exception_ContentNotFound {
            get {
                return ResourceManager.GetString("Exception_ContentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送邮件时产生异常{0} 的本地化字符串。
        /// </summary>
        public static string Exception_EmailUnableToSend {
            get {
                return ResourceManager.GetString("Exception_EmailUnableToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不允许频繁发帖 的本地化字符串。
        /// </summary>
        public static string Exception_FloodDenied {
            get {
                return ResourceManager.GetString("Exception_FloodDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到合法的Spacebuilder授权文件，请确保Web目录下存在后缀为lic的合法授权文件；如果您是商业客户，请到 http://www.spacebuilder.cn/Products/Contact 联系我们 的本地化字符串。
        /// </summary>
        public static string Exception_LicenseAuthorizeDenied {
            get {
                return ResourceManager.GetString("Exception_LicenseAuthorizeDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有发布{0}的权限 的本地化字符串。
        /// </summary>
        public static string Exception_PostAccessDenied {
            get {
                return ResourceManager.GetString("Exception_PostAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有进行回复的权限 的本地化字符串。
        /// </summary>
        public static string Exception_PostReplyAccessDenied {
            get {
                return ResourceManager.GetString("Exception_PostReplyAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁止注册 的本地化字符串。
        /// </summary>
        public static string Exception_RegisterDenied {
            get {
                return ResourceManager.GetString("Exception_RegisterDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I/O或无访问权限引发的异常 的本地化字符串。
        /// </summary>
        public static string Exception_UnauthorizedAccessException {
            get {
                return ResourceManager.GetString("Exception_UnauthorizedAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知错误 的本地化字符串。
        /// </summary>
        public static string Exception_UnknownError {
            get {
                return ResourceManager.GetString("Exception_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户“{0}”不存在或已被删除 的本地化字符串。
        /// </summary>
        public static string Exception_UserNotFound {
            get {
                return ResourceManager.GetString("Exception_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备制造厂商 的本地化字符串。
        /// </summary>
        public static string EXIFLabel_0x10F {
            get {
                return ResourceManager.GetString("EXIFLabel_0x10F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机型号 的本地化字符串。
        /// </summary>
        public static string EXIFLabel_0x110 {
            get {
                return ResourceManager.GetString("EXIFLabel_0x110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曝光时间 的本地化字符串。
        /// </summary>
        public static string EXIFLabel_0x829A {
            get {
                return ResourceManager.GetString("EXIFLabel_0x829A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 感光度 的本地化字符串。
        /// </summary>
        public static string EXIFLabel_0x8824 {
            get {
                return ResourceManager.GetString("EXIFLabel_0x8824", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍摄日期 的本地化字符串。
        /// </summary>
        public static string EXIFLabel_0x9003 {
            get {
                return ResourceManager.GetString("EXIFLabel_0x9003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大光圈 的本地化字符串。
        /// </summary>
        public static string EXIFLabel_0x9205 {
            get {
                return ResourceManager.GetString("EXIFLabel_0x9205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 闪光灯 的本地化字符串。
        /// </summary>
        public static string EXIFLabel_0x9209 {
            get {
                return ResourceManager.GetString("EXIFLabel_0x9209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 焦距 的本地化字符串。
        /// </summary>
        public static string EXIFLabel_0x920a {
            get {
                return ResourceManager.GetString("EXIFLabel_0x920a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宽度 的本地化字符串。
        /// </summary>
        public static string EXIFLabel_0xa002 {
            get {
                return ResourceManager.GetString("EXIFLabel_0xa002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高度 的本地化字符串。
        /// </summary>
        public static string EXIFLabel_0xa003 {
            get {
                return ResourceManager.GetString("EXIFLabel_0xa003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金币 的本地化字符串。
        /// </summary>
        public static string GoldCoin {
            get {
                return ResourceManager.GetString("GoldCoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 群组空间 的本地化字符串。
        /// </summary>
        public static string GroupSpace {
            get {
                return ResourceManager.GetString("GroupSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱已被占用&amp;lt;a href=&amp;quot;{0}&amp;quot;&amp;gt;[忘记密码？]&amp;lt;/a&amp;gt; 的本地化字符串。
        /// </summary>
        public static string Message_Pattern_RegisterFailedForDuplicateEmailAddress {
            get {
                return ResourceManager.GetString("Message_Pattern_RegisterFailedForDuplicateEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消激活用户 的本地化字符串。
        /// </summary>
        public static string NoActivateUser {
            get {
                return ResourceManager.GetString("NoActivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量激活了用户： {0} 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pattern_ActivateUser {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_ActivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 把 {0}：{1} 设置为通过审核 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pattern_Approved {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 依据规则自动取消管制了用户： {0} 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pattern_AutoNoModeratedUser {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_AutoNoModeratedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 封禁了用户： {0} 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pattern_BanUser {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_BanUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量取消激活了用户： {0} 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pattern_CancelActivateUser {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_CancelActivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 把 {0}：{1} 取消精华 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pattern_CancelEssential {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_CancelEssential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量取消管制了用户： {0} 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pattern_CancelModerateUser {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_CancelModerateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 把 {0}：{1} 取消置顶 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pattern_CancelSticky {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_CancelSticky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看了 {0}：{1} 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pattern_ControlledView {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_ControlledView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建了 {0}：{1} 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pattern_Create {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除了 {0}：{1} 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pattern_Delete {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除了用户 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pattern_DeleteUser {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 把 {0}：{1} 设置为未通过审核 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pattern_Disapproved {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_Disapproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量管制了用户： {0} 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pattern_ModerateUser {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_ModerateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消激活用户： {0} 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pattern_NoActivateUser {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_NoActivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对用户： {0}重设了密码 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pattern_ResetPassword {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 把 {0}：{1} 由 {2} 设置为 {3} 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pattern_SetCategory {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_SetCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 把 {0}：{1} 设置为精华 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pattern_SetEssential {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_SetEssential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 把 {0}：{1} 设置为置顶 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pattern_SetSticky {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_SetSticky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解禁了用户： {0} 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pattern_UnbanUser {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_UnbanUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新了 {0}：{1} 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pattern_Update {
            get {
                return ResourceManager.GetString("OperationLog_Pattern_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激活用户 的本地化字符串。
        /// </summary>
        public static string OperationType_ActivateUser {
            get {
                return ResourceManager.GetString("OperationType_ActivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通过审核 的本地化字符串。
        /// </summary>
        public static string OperationType_Approved {
            get {
                return ResourceManager.GetString("OperationType_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 封禁用户 的本地化字符串。
        /// </summary>
        public static string OperationType_BanUser {
            get {
                return ResourceManager.GetString("OperationType_BanUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消设置精华 的本地化字符串。
        /// </summary>
        public static string OperationType_CancelEssential {
            get {
                return ResourceManager.GetString("OperationType_CancelEssential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消设置精华 的本地化字符串。
        /// </summary>
        public static string OperationType_CancelSticky {
            get {
                return ResourceManager.GetString("OperationType_CancelSticky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建 的本地化字符串。
        /// </summary>
        public static string OperationType_Create {
            get {
                return ResourceManager.GetString("OperationType_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string OperationType_Delete {
            get {
                return ResourceManager.GetString("OperationType_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除用户 的本地化字符串。
        /// </summary>
        public static string OperationType_DeleteUser {
            get {
                return ResourceManager.GetString("OperationType_DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不通过审核 的本地化字符串。
        /// </summary>
        public static string OperationType_Disapproved {
            get {
                return ResourceManager.GetString("OperationType_Disapproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消激活用户 的本地化字符串。
        /// </summary>
        public static string OperationType_NoActivateUser {
            get {
                return ResourceManager.GetString("OperationType_NoActivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置精华 的本地化字符串。
        /// </summary>
        public static string OperationType_SetEssential {
            get {
                return ResourceManager.GetString("OperationType_SetEssential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 置顶 的本地化字符串。
        /// </summary>
        public static string OperationType_SetSticky {
            get {
                return ResourceManager.GetString("OperationType_SetSticky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解禁用户 的本地化字符串。
        /// </summary>
        public static string OperationType_UnbanUser {
            get {
                return ResourceManager.GetString("OperationType_UnbanUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重建索引 的本地化字符串。
        /// </summary>
        public static string OperationType_Update {
            get {
                return ResourceManager.GetString("OperationType_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新用户 的本地化字符串。
        /// </summary>
        public static string OperationType_UpdateUser {
            get {
                return ResourceManager.GetString("OperationType_UpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}：{1} 通过审核 的本地化字符串。
        /// </summary>
        public static string PointRecord_Pattern_Approved {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建了 {0}：{1} 的本地化字符串。
        /// </summary>
        public static string PointRecord_Pattern_Create {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}评论了:{1} 的本地化字符串。
        /// </summary>
        public static string PointRecord_Pattern_CreateComment {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_CreateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}成功邀请了用户{1}注册 的本地化字符串。
        /// </summary>
        public static string PointRecord_Pattern_CreateInviteFriendRecord {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_CreateInviteFriendRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除了 {0}：{1} 的本地化字符串。
        /// </summary>
        public static string PointRecord_Pattern_Delete {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}删除了评论：{1} 的本地化字符串。
        /// </summary>
        public static string PointRecord_Pattern_DeleteComment {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_DeleteComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}邀请的用户{1}被删除了 的本地化字符串。
        /// </summary>
        public static string PointRecord_Pattern_DeleteInvitedUser {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_DeleteInvitedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}：{1} 未通过审核 的本地化字符串。
        /// </summary>
        public static string PointRecord_Pattern_Disapproved {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_Disapproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首次上传头像 的本地化字符串。
        /// </summary>
        public static string PointRecord_Pattern_FirstUploadAvatar {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_FirstUploadAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关注了用户&quot;{0}&quot; 的本地化字符串。
        /// </summary>
        public static string PointRecord_Pattern_FollowUser {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_FollowUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}邀请的用户{1}成功解除了管制 的本地化字符串。
        /// </summary>
        public static string PointRecord_Pattern_FreeModeratedUser {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_FreeModeratedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反对了{0} 的本地化字符串。
        /// </summary>
        public static string PointRecord_Pattern_Oppose {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_Oppose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}：{1} 被管理员推荐 的本地化字符串。
        /// </summary>
        public static string PointRecord_Pattern_RecommendContent {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_RecommendContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您被管理员推荐 的本地化字符串。
        /// </summary>
        public static string PointRecord_Pattern_RecommendUser {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_RecommendUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}注册了帐号 的本地化字符串。
        /// </summary>
        public static string PointRecord_Pattern_Register {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}：{1} 被管理员设置为精华 的本地化字符串。
        /// </summary>
        public static string PointRecord_Pattern_SetEssential {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_SetEssential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}：{1} 被管理员设置为置顶 的本地化字符串。
        /// </summary>
        public static string PointRecord_Pattern_SetSticky {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_SetSticky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 赞同了{0} 的本地化字符串。
        /// </summary>
        public static string PointRecord_Pattern_Support {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户空间 的本地化字符串。
        /// </summary>
        public static string UserSpace {
            get {
                return ResourceManager.GetString("UserSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}无效 的本地化字符串。
        /// </summary>
        public static string Validate_DateType {
            get {
                return ResourceManager.GetString("Validate_DateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入电子邮箱 的本地化字符串。
        /// </summary>
        public static string Validate_EmailRequired {
            get {
                return ResourceManager.GetString("Validate_EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱格式不正确，请输入正确格式的邮箱地址 的本地化字符串。
        /// </summary>
        public static string Validate_EmailStyle {
            get {
                return ResourceManager.GetString("Validate_EmailStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昵称不允许使用，请选择其他昵称后注册 的本地化字符串。
        /// </summary>
        public static string Validate_NickNameIsDisallowed {
            get {
                return ResourceManager.GetString("Validate_NickNameIsDisallowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该昵称已被占用，请更换其他昵称重试 的本地化字符串。
        /// </summary>
        public static string Validate_NickNameIsExisting {
            get {
                return ResourceManager.GetString("Validate_NickNameIsExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只能输入字母、数字、汉字和下划线 的本地化字符串。
        /// </summary>
        public static string Validate_NickNameRegex {
            get {
                return ResourceManager.GetString("Validate_NickNameRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入昵称 的本地化字符串。
        /// </summary>
        public static string Validate_NickNameRequired {
            get {
                return ResourceManager.GetString("Validate_NickNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昵称长度最多{0}位 的本地化字符串。
        /// </summary>
        public static string Validate_NickNameTooLong {
            get {
                return ResourceManager.GetString("Validate_NickNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昵称长度不能少于{0}位 的本地化字符串。
        /// </summary>
        public static string Validate_NickNameTooShort {
            get {
                return ResourceManager.GetString("Validate_NickNameTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必须是数字 的本地化字符串。
        /// </summary>
        public static string Validate_NumericInvalid {
            get {
                return ResourceManager.GetString("Validate_NumericInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您输入的密码格式不正确 的本地化字符串。
        /// </summary>
        public static string Validate_PasswordRegex {
            get {
                return ResourceManager.GetString("Validate_PasswordRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的密码中特殊字符太少，请至少输入 {0} 个特殊字符（如：*、$等） 的本地化字符串。
        /// </summary>
        public static string Validate_Pattern_MinRequiredNonAlphanumericCharacters {
            get {
                return ResourceManager.GetString("Validate_Pattern_MinRequiredNonAlphanumericCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码长度不能少于 {0} 个字符 的本地化字符串。
        /// </summary>
        public static string Validate_Pattern_MinRequiredPasswordLength {
            get {
                return ResourceManager.GetString("Validate_Pattern_MinRequiredPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必须介于{1}和之{2}间 的本地化字符串。
        /// </summary>
        public static string Validate_Range {
            get {
                return ResourceManager.GetString("Validate_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 表达式：{1} 的本地化字符串。
        /// </summary>
        public static string Validate_RegularExpression {
            get {
                return ResourceManager.GetString("Validate_RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不能为空 的本地化字符串。
        /// </summary>
        public static string Validate_Required {
            get {
                return ResourceManager.GetString("Validate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能为空 的本地化字符串。
        /// </summary>
        public static string Validate_RequiredPassword {
            get {
                return ResourceManager.GetString("Validate_RequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}长度要求填写{2} 至 {1} 位 的本地化字符串。
        /// </summary>
        public static string Validate_StringLength {
            get {
                return ResourceManager.GetString("Validate_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该用户名不允许使用，请选择其他名字后注册 的本地化字符串。
        /// </summary>
        public static string Validate_UserNameIsDisallowed {
            get {
                return ResourceManager.GetString("Validate_UserNameIsDisallowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该用户名已被占用，请更换用户名重试 的本地化字符串。
        /// </summary>
        public static string Validate_UserNameIsExisting {
            get {
                return ResourceManager.GetString("Validate_UserNameIsExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只能输入字母、数字、汉字和下划线 的本地化字符串。
        /// </summary>
        public static string Validate_UserNameRegex {
            get {
                return ResourceManager.GetString("Validate_UserNameRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入用户名 的本地化字符串。
        /// </summary>
        public static string Validate_UserNameRequired {
            get {
                return ResourceManager.GetString("Validate_UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名长度最多{0}位 的本地化字符串。
        /// </summary>
        public static string Validate_UserNameTooLong {
            get {
                return ResourceManager.GetString("Validate_UserNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名长度不能少于{0}位 的本地化字符串。
        /// </summary>
        public static string Validate_UserNameTooShort {
            get {
                return ResourceManager.GetString("Validate_UserNameTooShort", resourceCulture);
            }
        }
    }
}
